### ISSUE TITLE
Fatal error: malformed or corrupted AST file: 'Invalid SEMA_DECL_REFS block'

### ISSUE THREAD

**Issue by a-aamir** [abyzovlab/CNVnator#178]
Hi, 

New to CNVnator. Havent got far along the process and have encountered a fatal error. Not sure how to proceed, help much appreciated! 

(Currently have cnvnator/deps/root-6.12.04/etc/cling/lib/clang/5.0.0) 

This is the error: 

ERROR in cling::CIFactory::createCI():
  resource directory /cm/shared/apps/cnvnator/deps/root-6.12.04/etc/cling/lib/clang/3.9.0 not found!
fatal error: malformed or corrupted AST file: 'Invalid SEMA_DECL_REFS block'

 *** Break *** segmentation violation

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00002aaaadaf841c in __libc_waitpid (pid=8746, stat_loc=stat_loc
entry=0x7fffffd9a360, options=options
entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:31
#1  0x00002aaaada75f12 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:148
#2  0x00002aaaab1e4e6f in TUnixSystem::StackTrace() () from /cm/shared/apps/cnvnator/deps/root-6.12.04/lib/libCore.so
#3  0x00002aaaab1e759c in TUnixSystem::DispatchSignals(ESignals) () from /cm/shared/apps/cnvnator/deps/root-6.12.04/lib/libCore.so
#4  <signal handler called>
#5  0x00002aac5c018eb2 in clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) () from /cm/shared/apps//ROOT/6.10.02/lib/libCling.so
#6  0x00002aac5b110cfc in cling::IncrementalParser::ParseInternal(llvm::StringRef) () from /cm/shared/apps//ROOT/6.10.02/lib/libCling.so
#7  0x00002aac5b111bec in cling::IncrementalParser::Compile(llvm::StringRef, cling::CompilationOptions const&) () from /cm/shared/apps//ROOT/6.10.02/lib/libCling.so
#8  0x00002aac5b0b89ac in cling::Interpreter::DeclareInternal(std::string const&, cling::CompilationOptions const&, cling::Transaction**) const () from /cm/shared/apps//ROOT/6.10.02/lib/libCling.so
#9  0x00002aac5b0b8aee in cling::Interpreter::declare(std::string const&, cling::Transaction**) () from /cm/shared/apps//ROOT/6.10.02/lib/libCling.so
#10 0x00002aac5b062c42 in TCling::TCling(char const*, char const*) () from /cm/shared/apps//ROOT/6.10.02/lib/libCling.so
#11 0x00002aac5b06383e in CreateInterpreter () from /cm/shared/apps//ROOT/6.10.02/lib/libCling.so
#12 0x00002aaaab053138 in TROOT::InitInterpreter() () from /cm/shared/apps/cnvnator/deps/root-6.12.04/lib/libCore.so
#13 0x00002aaaab053596 in ROOT::Internal::GetROOT2() () from /cm/shared/apps/cnvnator/deps/root-6.12.04/lib/libCore.so
#14 0x00002aaaab0e6076 in TEnv::Getvalue(char const*) const () from /cm/shared/apps/cnvnator/deps/root-6.12.04/lib/libCore.so
#15 0x00002aaaab0e6709 in TEnv::GetValue(char const*, char const*) const () from /cm/shared/apps/cnvnator/deps/root-6.12.04/lib/libCore.so
#16 0x00002aaaab13b29e in TUrl::GetSpecialProtocols() () from /cm/shared/apps/cnvnator/deps/root-6.12.04/lib/libCore.so
#17 0x00002aaaab13b99e in TUrl::SetUrl(char const*, bool) () from /cm/shared/apps/cnvnator/deps/root-6.12.04/lib/libCore.so
#18 0x00002aaaab13c004 in TUrl::TUrl(char const*, bool) () from /cm/shared/apps/cnvnator/deps/root-6.12.04/lib/libCore.so
#19 0x00002aaaab65f2f0 in TFile::TFile(char const*, char const*, char const*, int) () from /cm/shared/apps/cnvnator/deps/root-6.12.04/lib/libRIO.so
#20 0x0000000000427a9b in HisMaker::writeTreeForChromosome(std::string, short*, short*, int) ()
#21 0x000000000043ba72 in HisMaker::produceTrees(std::string*, int, std::string*, int, bool) ()
#22 0x0000000000409adf in main ()
===========================================================

The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum.
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00002aac5c018eb2 in clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) () from /cm/shared/apps//ROOT/6.10.02/lib/libCling.so
#6  0x00002aac5b110cfc in cling::IncrementalParser::ParseInternal(llvm::StringRef) () from /cm/shared/apps//ROOT/6.10.02/lib/libCling.so
#7  0x00002aac5b111bec in cling::IncrementalParser::Compile(llvm::StringRef, cling::CompilationOptions const&) () from /cm/shared/apps//ROOT/6.10.02/lib/libCling.so
#8  0x00002aac5b0b89ac in cling::Interpreter::DeclareInternal(std::string const&, cling::CompilationOptions const&, cling::Transaction**) const () from /cm/shared/apps//ROOT/6.10.02/lib/libCling.so
#9  0x00002aac5b0b8aee in cling::Interpreter::declare(std::string const&, cling::Transaction**) () from /cm/shared/apps//ROOT/6.10.02/lib/libCling.so
#10 0x00002aac5b062c42 in TCling::TCling(char const*, char const*) () from /cm/shared/apps//ROOT/6.10.02/lib/libCling.so
#11 0x00002aac5b06383e in CreateInterpreter () from /cm/shared/apps//ROOT/6.10.02/lib/libCling.so
#12 0x00002aaaab053138 in TROOT::InitInterpreter() () from /cm/shared/apps/cnvnator/deps/root-6.12.04/lib/libCore.so
#13 0x00002aaaab053596 in ROOT::Internal::GetROOT2() () from /cm/shared/apps/cnvnator/deps/root-6.12.04/lib/libCore.so
#14 0x00002aaaab0e6076 in TEnv::Getvalue(char const*) const () from /cm/shared/apps/cnvnator/deps/root-6.12.04/lib/libCore.so
#15 0x00002aaaab0e6709 in TEnv::GetValue(char const*, char const*) const () from /cm/shared/apps/cnvnator/deps/root-6.12.04/lib/libCore.so
#16 0x00002aaaab13b29e in TUrl::GetSpecialProtocols() () from /cm/shared/apps/cnvnator/deps/root-6.12.04/lib/libCore.so
#17 0x00002aaaab13b99e in TUrl::SetUrl(char const*, bool) () from /cm/shared/apps/cnvnator/deps/root-6.12.04/lib/libCore.so
#18 0x00002aaaab13c004 in TUrl::TUrl(char const*, bool) () from /cm/shared/apps/cnvnator/deps/root-6.12.04/lib/libCore.so
#19 0x00002aaaab65f2f0 in TFile::TFile(char const*, char const*, char const*, int) () from /cm/shared/apps/cnvnator/deps/root-6.12.04/lib/libRIO.so
#20 0x0000000000427a9b in HisMaker::writeTreeForChromosome(std::string, short*, short*, int) ()
#21 0x000000000043ba72 in HisMaker::produceTrees(std::string*, int, std::string*, int, bool) ()
#22 0x0000000000409adf in main ()
===========================================================

Thank you !

**Comment by a-aamir** [comment]
So finally managed to find the 3.9.0 clang folder, put it into the root folder and the error seems to have been overcome.
