### ISSUE TITLE
ERROR plotcircular.py

### ISSUE THREAD

**Issue by bucongfan** [abyzovlab/CNVnator#253]
There are some error happens:
Traceback (most recent call last):
  File "CNVnator-master/plotcircular.py", line 54, in <module>
    snp = iof.get_signal(c, bs, "SNP maf",snpflag)[1]
  File "biosoft/CNVnator-master/pytools/io.py", line 121, in get_signal
    his = self.file.Get("bin_" + str(bin_size)).Get(self.signal_name(chr, bin_size, signal, flags))
AttributeError: 'TObject' object has no attribute 'Get'
Exception ignored in: <function IO.__del__ at 0x7f6cfa35c940>
Traceback (most recent call last):
  File "CNVnator-master/pytools/io.py", line 62, in __del__
AttributeError: 'CPyCppyy_NoneType' object has no attribute 'Close'

Is the CNV drawing scripts such as plotcircular not included in conda?

**Comment by suvakov** [comment]
It should be included. Do you have SNP data imported and SNP histograms (-baf step) generated for all chromosomes?

**Comment by bucongfan** [comment]
Thank you very much for your help!
