### ISSUE TITLE
*** Break *** segmentation violation

### ISSUE THREAD

**Issue by anubhabkhan** [abyzovlab/CNVnator#259]
Hi,

I am trying to run CNVnator on a bam file but get a "segmentation violation" issue. I also tried splitting the bam file into single chromosomes as explained in "https://github.com/abyzovlab/CNVnator/issues/245" but I get the following error. Any help on how to avoid this error would be very helpful.

*** Break *** segmentation violation

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f5c5e07c4fc in waitpid () from /lib64/libc.so.6
#1  0x00007f5c5dff9fb2 in do_system () from /lib64/libc.so.6
#2  0x00007f5c60c2b0c4 in TUnixSystem::StackTrace() () from /softwares/CNVnator_v0.4.1/root/lib/libCore.so.6.18
#3  0x00007f5c60c2d7fc in TUnixSystem::DispatchSignals(ESignals) () from /softwares/CNVnator_v0.4.1/root/lib/libCore.so.6.18
#4  <signal handler called>
#5  0x00007f5c5ed4a59d in ?? () from /lib64/libstdc++.so.6
#6  0x00007f5c5edae09e in std::string::assign(std::string const&) () from /lib64/libstdc++.so.6
#7  0x00000000004695c0 in HisMaker::produceTrees(std::string*, int, std::string*, int, bool) ()
#8  0x000000000040b1d5 in main ()
===========================================================

The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00007f5c5ed4a59d in ?? () from /lib64/libstdc++.so.6
#6  0x00007f5c5edae09e in std::string::assign(std::string const&) () from /lib64/libstdc++.so.6
#7  0x00000000004695c0 in HisMaker::produceTrees(std::string*, int, std::string*, int, bool) ()
#8  0x000000000040b1d5 in main ()
===========================================================

**Comment by abyzov** [comment]
Hi,
the message is not that informative. But are you able to run ROOT on its own?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
