### ISSUE TITLE
*** Break *** segmentation violation

### ISSUE THREAD

**Issue by ZYongQi** [abyzovlab/CNVnator#279]
### CNVnator   *** Break *** segmentation violation

**Hi,here is ZYongQi. I got some errors when i tried to run the first step like this :**

`cnvnator -root ailun.root -tree ailun.bam -chrom NC_048218.1`

**However,it doesn't work but show like this :**

```
 *** Break *** segmentation violation
 Generating stack trace...
 0x00007fa2d99f1830 in __libc_start_main + 0xf0 from /lib/x86_64-linux-gnu/libc.so.6
 0x0000000000410b59 in <unknown> from cnvnator
```
**And this is what my ailun.bam shows:**

```
@HD     VN:1.6  SO:coordinate
@SQ     SN:NC_048218.1  LN:212770937
@SQ     SN:NC_048219.1  LN:199809881
@SQ     SN:NC_048220.1  LN:147627920
@SQ     SN:NC_048221.1  LN:144794249
@SQ     SN:NC_048222.1  LN:130990914
@SQ     SN:NC_048223.1  LN:131587389
@SQ     SN:NC_048224.1  LN:141533052
```
**And  the corresponding version of the softwares are as follows:**
CNVnatorv_0.4.1    
ROOT-6.18/00     
samtools-1.10 
and all of them run normally.

By the way , I have tried ROOT-5.34 , but it doesn't work.And it seems to be incompatible with CNVnatorv_0.4.1.
Any ideas why this happens? And any recommendation to get it solved?
Thank you in advance,sincerely.
ZYongQi

**Comment by abyzov** [comment]
Hi,
this may happen if you have too many contigs in your genome.
How many do you have?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 7-91
Rochester, MN 55905
www.abyzovlab.org
tel: +1-(507)-538-0978

**Comment by ZYongQi** [comment]
> Hi, this may happen if you have too many contigs in your genome. How many do you have? Alexej Abyzov, Ph.D. Senior Associate Consultant, Associate Professor of Biomedical Informatics, Department of Quantitative Health Sciences, Center for Individualized Medicine, Mayo Clinic ----------------------------- Mayo Clinic, 200 1st street SW, Harwick 7-91 Rochester, MN 55905 [www.abyzovlab.org](http://www.abyzovlab.org) tel: +1-(507)-538-0978

**Comment by ZYongQi** [comment]
> Hi, this may happen if you have too many contigs in your genome. How many do you have? Alexej Abyzov, Ph.D. Senior Associate Consultant, Associate Professor of Biomedical Informatics, Department of Quantitative Health Sciences, Center for Individualized Medicine, Mayo Clinic ----------------------------- Mayo Clinic, 200 1st street SW, Harwick 7-91 Rochester, MN 55905 [www.abyzovlab.org](http://www.abyzovlab.org) tel: +1-(507)-538-0978

**Hi,this is ZYongQi.Thank you for your advice.**
This is number of contigs:
```
zyq@Godzilla:~/out$ samtools view -H ailun.bam |grep "@SQ" |wc -l
**73514**
```
and the value of N_CHROM_MAX is **20000**.

I raised its value to 100000，and recompiled my cnvnator.But simmilar error occurred like this :
```
zyq@Godzilla:~/out$ cnvnator -root ailun.root -tree ailun.bam -chrom NC_048218.1
Segmentation fault
```
Are there any issues with my modifications in this step ?

**Comment by Dorothy-7273** [comment]
Hi ,I met the same question as you,and I also use the NC_ format,I have a guess if the cnvnator is not suitable for NC_ format chromosome?

**Comment by Dorothy-7273** [comment]
to deal with this error,I split a chromosome from the bam file to test,but it also :
"*** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00002ad7ade9860c in waitpid () from /lib64/libc.so.6
#1  0x00002ad7ade15f62 in do_system () from /lib64/libc.so.6
#2  0x00002ad7ac847c44 in TUnixSystem::StackTrace() () from /public5/home/sch5314/.conda/envs/cnvnator/bin/../lib/libCore.so.6.20
#3  0x00002ad7ac84a77e in TUnixSystem::DispatchSignals(ESignals) () from /public5/home/sch5314/.conda/envs/cnvnator/bin/../lib/libCore.so.6.20
#4  <signal handler called>
#5  0x00002ad7adf2ef88 in __memmove_ssse3_back () from /lib64/libc.so.6
#6  0x0000556c3b687924 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#7  0x0000556c3b6cb12d in HisMaker::produceTrees(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, bool) ()
#8  0x0000556c3b6844e9 in main ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00002ad7adf2ef88 in __memmove_ssse3_back () from /lib64/libc.so.6
#6  0x0000556c3b687924 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#7  0x0000556c3b6cb12d in HisMaker::produceTrees(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, bool) ()
#8  0x0000556c3b6844e9 in main ()
===========================================================

**Comment by abyzov** [comment]
Hi,
to find out the cause we’d have to get your files and debug on our system.
I would suggest to try using CNVpytor which is the successor of CNVnator and is being maintained and extended.
<https://github.com/abyzovlab/CNVpytor>
[CNVpytor.png]
abyzovlab/CNVpytor: a python extension of CNVnator -- a tool for CNV analysis from depth-of-coverage by mapped reads<https://github.com/abyzovlab/CNVpytor>
github.com<https://github.com/abyzovlab/CNVpytor>


Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 7-91
Rochester, MN 55905
www.abyzovlab.org
tel: +1-(507)-538-0978

**Comment by ZYongQi** [comment]
> Hi, to find out the cause we’d have to get your files and debug on our system. I would suggest to try using CNVpytor which is the successor of CNVnator and is being maintained and extended. <https://github.com/abyzovlab/CNVpytor> [CNVpytor.png] abyzovlab/CNVpytor: a python extension of CNVnator -- a tool for CNV analysis from depth-of-coverage by mapped reads<https://github.com/abyzovlab/CNVpytor> github.com<https://github.com/abyzovlab/CNVpytor> Alexej Abyzov, Ph.D. Senior Associate Consultant, Associate Professor of Biomedical Informatics, Department of Quantitative Health Sciences, Center for Individualized Medicine, Mayo Clinic ----------------------------- Mayo Clinic, 200 1st street SW, Harwick 7-91 Rochester, MN 55905 [www.abyzovlab.org](http://www.abyzovlab.org) tel: +1-(507)-538-0978

All right,thank you for your advise.We'll try CNVpytor.
